### ISSUE TITLE
HU2005-Estructura inicial proyecto-3

### ISSUE THREAD

**Issue by gdgalvis** [Ignis-Uninorte/PRJ2-MVP1#1]
En esta historia de usuario se deberá crear el
proyecto inicial y la estructura de diseño y
navegación. Se debe ser cuidadoso porque esta es la
única historia de usuario pre-requisito que se
necesita para ejecutar las demás. Con base a la
implementación de esta estructura inicial, el equipo
continuará desarrollando de forma paralela y
asincrónicamente los demás componentes y
páginas.

**Comment by caheras** [comment]
## Quality Assurance Requirements

### Desktop QA
1. [x]  Se debe visualizar la página de inicio con tres secciones sin información, header, subheader, content y footer. 
2. [x] Cada sección puede estar resaltada con un background o borde de color específico y un texto ejemplo/temporal que la identifique 

### Mobile QA
1. [x] La página de inicio debe visualizarse con tres secciones sin información: header, subheader, contenido, y footer.
2. [x] Cada sección puede estar resaltada con un background o borde de color específico y un texto ejemplo/temporal que la identifique

## Media 
### Desktop
![Image](https://github.com/user-attachments/assets/f8a2f208-a213-4730-99e3-b80d054901f8)
### Mobile
![Image](https://github.com/user-attachments/assets/124b5d98-908d-48c6-a293-a8b6c895e8a5)
