### ISSUE TITLE
HU2007- Página inicio: sub header y menú de navegación-3

### ISSUE THREAD

**Issue by gdgalvis** [Ignis-Uninorte/PRJ2-MVP1#3]

**Comment by caheras** [comment]
## Quality Assurance Requirements - Subheader and Navigation Menu

### Desktop QA
1. [ ] Se debe visualizar la página de inicio con el subheader y su menú de navegación. Cada opción por categoría (aplica para todas) deberá tener el enlace a su respectivo PLP.
2. [x] El subheader con el menú de navegación deben ser responsive.

### Mobile QA
1. [ ] Se debe visualizar la página de inicio con el subheader y su menú de navegación. Cada opción por categoría (aplica para todas) deberá tener el enlace a su respectivo PLP.
2. [x] El subheader con el menú de navegación deben ser responsive.
![image](https://github.com/user-attachments/assets/30130912-9160-4f94-963c-45f986d29a46)
![image](https://github.com/user-attachments/assets/c365b8fd-5952-45c8-aa6c-4a9cbbaf67af)
