### ISSUE TITLE
HU2008-Página de inicio: footer - 1

### ISSUE THREAD

**Issue by gdgalvis** [Ignis-Uninorte/PRJ2-MVP1#4]

**Comment by caheras** [comment]
## Quality Assurance Requirements - Footer

### Desktop QA
1. [x] Se debe visualizar la página de inicio con el footer.
2. [x] El footer debe ser responsive.

### Mobile QA
1. [x] Se debe visualizar la página de inicio con el footer.
2. [x] El footer debe ser responsive.

![image](https://github.com/user-attachments/assets/32208140-645b-4c75-8529-b96e7167b761)
![image](https://github.com/user-attachments/assets/91633e68-164f-4a28-89dc-53f2b81d670a)
