### ISSUE TITLE
HU2011-Página inicio: productos destacados - 13

### ISSUE THREAD

**Issue by gdgalvis** [Ignis-Uninorte/PRJ2-MVP1#7]

**Comment by caheras** [comment]
## Quality Assurance Requirements - Featured Products

### Desktop QA
1. [x] Se debe visualizar en la página de inicio los productos destacados en el contenido central. Tener en cuenta la posición que le corresponde.
2. [x] Al hacer clic en el producto destacado, este deberá redireccionar al PDP del producto.
3. [x] El botón o enlace de agregar al carrito en el producto destacado, no debe redireccionar al PDP del producto.
4. [x] Los productos destacados deben tener comportamiento responsive.

### Mobile QA
1. [x] Se debe visualizar en la página de inicio los productos destacados en el contenido central. Tener en cuenta la posición que le corresponde.
2. [x] Al hacer clic en el producto destacado, este deberá redireccionar al PDP del producto.
3. [x] El botón o enlace de agregar al carrito en el producto destacado, no debe redireccionar al PDP del producto.
4. [x] Los productos destacados deben tener comportamiento responsive.
![image](https://github.com/user-attachments/assets/9c3c4467-b7a4-4962-8cbf-f0e773e63b9c)
![image](https://github.com/user-attachments/assets/0521ac77-481c-41e2-a1b6-9a55c342eaa4)
![image](https://github.com/user-attachments/assets/b8677481-c38d-45a4-b21f-a04497bf5dc0)
![image](https://github.com/user-attachments/assets/5f214ad8-2271-4b8f-88c6-852f697c4314)
